/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.glb 
Author: CG Robot (https://sketchfab.com/cgrobot)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/windows-10-laptop-6734c1552bcd4b1b8bab405b8cd23773
Title: Windows 10 Laptop
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.007']} />
    </group>
  )
}

useGLTF.preload('/models/laptop.glb')
